import {
  Search, ChevronRight, ChevronLeft, ArrowLeft, ArrowRight,
  Star, StarHalf, StarOff, Heart, HeartOff,
  ShoppingCart, Package, PackageOpen, Store, MapPin, Phone, Mail,
  Globe, Play as PlayIcon, BadgeCheck, Check, CheckCircle2,
  X, XCircle, Bookmark, BookmarkCheck,
  Pencil, LogOut, Upload, CloudUpload, User, Users, UserPlus, UserX,
  Calendar, Clock, CreditCard, Smartphone, Landmark, Lock, KeyRound,
  Send, Info, AlertTriangle, AlertCircle, Flame, Eye, EyeOff,
  Truck, RotateCcw, ShieldCheck, Minus, Plus, Image,
  Wrench, Camera, Code, Megaphone, Handshake, Lightbulb, Gem,
  Headphones, BatteryCharging, Bluetooth, Zap, Droplets, Fingerprint,
  Paintbrush as DesignServices, Leaf, LifeBuoy, CircleDot, Sparkles,
  TrendingUp, TrendingDown, Minus as TrendingFlat, BarChart3, FileText,
  Download, Trash2, RefreshCw, Flag, ExternalLink,
  LayoutDashboard, ClipboardList, Shield, PieChart,
  Menu, PanelLeftOpen, Ban, PlayCircle, PauseCircle, Save,
  CircleDollarSign, Receipt, Wallet, DollarSign,
  Contact, HeartCrack, Layers,
  ChevronDown, Settings, Filter, SlidersHorizontal,
  SearchX, Loader2, Bot, CircleCheckBig,
  TableProperties, FileSpreadsheet, FileDown,
  Blocks, Award, GraduationCap, Building2,
  ListTodo, PersonStanding, UserCog, ClipboardCheck
} from 'lucide-vue-next'


export const iconMap = {
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  menu: Menu,
  menu_open: PanelLeftOpen,
  close: X,
  
  search: Search,
  search_off: SearchX,
  
  check: Check,
  check_circle: CheckCircle2,
  cancel: XCircle,
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  
  shopping_cart: ShoppingCart,
  shopping_bag: Package,
  inventory_2: Package,
  inventory: PackageOpen,
  favorite: Heart,
  favorite_border: HeartOff,
  heart_broken: HeartCrack,
  bookmark: BookmarkCheck,
  bookmark_border: Bookmark,
  star: Star,
  star_half: StarHalf,
  star_outline: StarOff,
  star_border: StarOff,
  
  person: User,
  people: Users,
  person_add: UserPlus,
  person_off: UserX,
  groups: Users,
  contact_mail: Contact,
  contact_support: LifeBuoy,
  assignment_ind: UserCog,
  
  edit: Pencil,
  delete: Trash2,
  delete_sweep: Trash2,
  save: Save,
  add: Plus,
  remove: Minus,
  send: Send,
  download: Download,
  cloud_upload: CloudUpload,
  refresh: RefreshCw,
  sync: Loader2,
  login: LogOut,
  logout: LogOut,
  
  store: Store,
  storefront: Store,
  payments: Wallet,
  payment: CreditCard,
  credit_card: CreditCard,
  phone_android: Smartphone,
  account_balance: Landmark,
  lock: Lock,
  lock_reset: KeyRound,
  
  local_shipping: Truck,
  campaign: Megaphone,
  camera_alt: Camera,
  code: Code,
  engineering: Wrench,
  design_services: DesignServices,
  
  description: FileText,
  article: FileText,
  picture_as_pdf: FileText,
  add_chart: BarChart3,
  assessment: BarChart3,
  analytics: PieChart,
  
  calendar_today: Calendar,
  schedule: Clock,
  
  location_on: MapPin,
  
  phone: Phone,
  mail: Mail,
  language: Globe,
  smart_display: PlayIcon,
  mark_email_read: Mail,
  
  auto_awesome: Sparkles,
  local_fire_department: Flame,
  visibility: Eye,
  replay: RotateCcw,
  diamond: Gem,
  eco: Leaf,
  lightbulb: Lightbulb,
  handshake: Handshake,
  touch_app: Fingerprint,
  water_drop: Droplets,
  speed: Zap,
  bluetooth: Bluetooth,
  battery_charging_full: BatteryCharging,
  noise_aware: Headphones,
  category: Layers,
  workspace_premium: Award,
  
  trending_up: TrendingUp,
  trending_flat: TrendingFlat,
  block: Ban,
  play_circle: PlayCircle,
  pause_circle: PauseCircle,
  flag: Flag,
  open_in_new: ExternalLink,
  
  dashboard: LayoutDashboard,
  assignment: ClipboardList,
  done_all: ClipboardCheck,
  task_alt: CircleCheckBig,
  table_chart: TableProperties,
  support_agent: LifeBuoy,
  
  photo: Image,
  school: GraduationCap,
  cleaning_services: Sparkles,
  shield: Shield,
  print: FileSpreadsheet,
}


export function getLucideIcon(materialIconName) {
  return iconMap[materialIconName] || Info
}

export {
  Search, ChevronRight, ChevronLeft, ArrowLeft, ArrowRight,
  Star, StarHalf, StarOff, Heart, HeartOff,
  ShoppingCart, Package, PackageOpen, Store, MapPin, Phone, Mail,
  Globe, PlayIcon, BadgeCheck, Check, CheckCircle2,
  X, XCircle, Bookmark, BookmarkCheck,
  Pencil, LogOut, CloudUpload, User, Users, UserPlus, UserX,
  Calendar, Clock, CreditCard, Smartphone, Landmark, Lock, KeyRound,
  Send, Info, AlertTriangle, AlertCircle, Flame, Eye,
  Truck, RotateCcw, ShieldCheck, Minus, Plus, Image,
  Wrench, Camera, Code, Megaphone, Handshake, Lightbulb, Gem,
  Headphones, BatteryCharging, Bluetooth, Zap, Droplets, Fingerprint,
  Leaf, LifeBuoy, Sparkles,
  TrendingUp, BarChart3, FileText,
  Download, Trash2, RefreshCw, Flag, ExternalLink,
  LayoutDashboard, ClipboardList, Shield, PieChart,
  Menu, PanelLeftOpen, Ban, PlayCircle, PauseCircle, Save,
  Wallet, Receipt,
  Contact, HeartCrack, Layers,
  SearchX, Loader2, CircleCheckBig,
  TableProperties, FileSpreadsheet, FileDown,
  Award, Building2,
  ClipboardCheck, UserCog
}
